import { StyleSheet } from "react-native";

export const getStatisticsStyles = (theme: {
  colors: Record<string, string>;
}) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.colors.background },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: theme.colors.card,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.cardBorder,
    },
    headerBtn: { padding: 4 },
    headerTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: theme.colors.textMain,
      flex: 1,
      textAlign: "center",
    },
    headerRight: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    segmentContainer: {
      flexDirection: "row",
      backgroundColor: theme.colors.cardBorder,
      margin: 16,
      marginBottom: 0,
      borderRadius: 12,
      padding: 4,
    },
    segmentBtn: {
      flex: 1,
      paddingVertical: 10,
      alignItems: "center",
      borderRadius: 10,
    },
    segmentBtnActive: {
      backgroundColor: theme.colors.primaryDark,
      elevation: 2,
    },
    segmentText: {
      fontSize: 13,
      fontWeight: "700",
      color: theme.colors.textMuted,
    },
    segmentTextActive: { color: "#fff" },
    card: {
      backgroundColor: theme.colors.card,
      borderRadius: 20,
      borderWidth: 2,
      borderColor: theme.colors.cardBorder,
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      padding: 18,
      alignItems: "center",
    },
    sectionTitle: {
      fontWeight: "900",
      color: theme.colors.textMain,
      fontSize: 13,
      textTransform: "uppercase",
    },
    table: {
      paddingHorizontal: 18,
      paddingBottom: 18,
      borderTopWidth: 2,
      borderTopColor: theme.colors.background,
    },
    rowHeader: { flexDirection: "row", paddingTop: 12, marginBottom: 8 },
    colNameWrap: { flex: 1.5, flexDirection: "row", alignItems: "center" },
    colWrap: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
    },
    colText: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.colors.textLight,
    },
    row: {
      flexDirection: "row",
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.background,
    },
    cellName: {
      flex: 1.5,
      fontSize: 15,
      fontWeight: "700",
      color: theme.colors.textMain,
    },
    cell: {
      flex: 1,
      fontSize: 15,
      fontWeight: "600",
      color: theme.colors.textMuted,
      textAlign: "center",
    },
    hitPlayerHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 10,
      marginBottom: 6,
    },
    hitPlayerName: {
      fontSize: 13,
      fontWeight: "800",
      color: theme.colors.primary,
      textTransform: "uppercase",
    },
    hitRow: {
      flexDirection: "row",
      paddingVertical: 6,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.background,
    },
    hitCellTarget: {
      flex: 1.5,
      fontSize: 14,
      fontWeight: "800",
      color: theme.colors.textMain,
    },
    hitCell: {
      flex: 1,
      fontSize: 14,
      fontWeight: "600",
      color: theme.colors.textMuted,
      textAlign: "center",
    },
    emptyText: {
      textAlign: "center",
      padding: 20,
      color: theme.colors.textLight,
      fontStyle: "italic",
      fontWeight: "bold",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      padding: 20,
    },
    modalContent: {
      backgroundColor: theme.colors.card,
      borderRadius: 30,
      padding: 25,
      maxHeight: "85%",
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "900",
      marginBottom: 10,
      color: theme.colors.textMain,
      textAlign: "center",
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.background,
      borderRadius: 10,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: theme.colors.cardBorder,
      marginBottom: 12,
    },
    searchInput: {
      flex: 1,
      paddingVertical: 10,
      paddingLeft: 8,
      color: theme.colors.textMain,
      fontSize: 16,
    },
    selectAllRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 10,
      paddingHorizontal: 4,
    },
    selectAllLabel: {
      fontSize: 13,
      fontWeight: "700",
      color: theme.colors.textMuted,
    },
    selectAllText: {
      fontSize: 14,
      fontWeight: "800",
      color: theme.colors.primary,
    },
    filterRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.background,
    },
    filterRowText: {
      fontSize: 17,
      fontWeight: "600",
      color: theme.colors.textMain,
    },
    closeBtn: {
      backgroundColor: theme.colors.primary,
      padding: 18,
      borderRadius: 15,
      marginTop: 20,
      alignItems: "center",
    },
    closeBtnText: { color: "#fff", fontWeight: "800", fontSize: 16 },
  });
